version: 1
disable_existing_loggers: no
formatters:
  console_formatter_game:
    (): my_app.game.logger.ConsoleFormatter
  # console_formatter_backend:
  #   (): src.logger.ConsoleFormatter
handlers:
  # console_handler_backend:
  #   class: logging.StreamHandler
  #   formatter: console_formatter_backend
  console_handler_game:
    class: logging.StreamHandler
    formatter: console_formatter_game
root:
  level: INFO
  handlers: [console_handler_game]
  'game_logger':
    level: INFO
    propagate: no
    handlers: [console_handler_game]
  'uvicorn':
    level: INFO
    propagate: yes
