MATCHES_QUEUE = "matches"
GAME_MATCH_EXCHANGE = "game_match_exchange"
MATCHMAKER_MATCH_EXCHANGE = "matchmaker_match_exchange"
USER_MATCH_EXCHANGE = "user_match_exchange"
USER_QUEUE_KEY = "user_match.{user_id}"
