services:
  db:
    image: postgres:13.2
    ports:
      - "6969:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      retries: 20
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  # game_app:
  #   build: .
  #   command: scripts/startup.sh
  #   volumes:
  #     - "./:/code"
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - config/.env

  rabbitmq:
    image: rabbitmq:3.13.7-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

networks:
 sirius:
   external: true
