# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
from typing import Optional
import uuid


@dataclasses.dataclass()
class Game:
    id: uuid.UUID
    winner_id: Optional[int]


@dataclasses.dataclass()
class Player:
    id: int
    rating: Optional[int]


@dataclasses.dataclass()
class PlayerGame:
    player_id: int
    game_id: uuid.UUID
